import type { AudioTrack, PlaylistCategory } from '../types/audio';

interface AudioManifestEntry {
  category: string;
  fileName: string;
}

const validCategories: PlaylistCategory[] = [
  'presentation',
  'point_intros',
  'technical_timeouts',
  'super_spike',
  'monster_block',
  'fire_ball',
  'ace',
  'timeout_continuous',
  'awards',
];

const durationMap: Record<PlaylistCategory, number> = {
  presentation: 180,
  point_intros: 12,
  technical_timeouts: 60,
  super_spike: 12,
  monster_block: 12,
  fire_ball: 12,
  ace: 12,
  timeout_continuous: 180,
  awards: 180,
};

/**
 * Discovers built-in audio files.
 *
 * Primary path: queries Supabase `tracks` table for rows where `is_built_in = true`.
 *               These are tracks pre-loaded by the operator directly into Supabase Storage.
 *
 * Fallback path: fetches `/audio-manifest.json` generated by the Vite `audioManifestPlugin`
 *               from files placed in `public/audio/<category>/`. Used for local development
 *               without Supabase credentials.
 */
export class FolderScannerService {
  private static cachedTracksPromise: Promise<AudioTrack[]> | null = null;

  public static scanAudioFolders(): Promise<AudioTrack[]> {
    if (!this.cachedTracksPromise) {
      this.cachedTracksPromise = this.doScan();
    }
    return this.cachedTracksPromise;
  }

  /** Bust the cache — call after uploading a built-in track so next load picks it up. */
  public static clearCache(): void {
    this.cachedTracksPromise = null;
  }

  private static async doScan(): Promise<AudioTrack[]> {
    const supabaseUrl = import.meta.env.NEXT_PUBLIC_SUPABASE_URL as string | undefined;

    if (supabaseUrl) {
      return this.scanFromSupabase();
    }

    // Fallback: legacy public/audio/ manifest (local dev without Supabase)
    return this.scanFromManifest();
  }

  /**
   * Query Supabase `tracks` table for is_built_in = true rows.
   * The storage_path is resolved to a public URL via Supabase Storage.
   */
  private static async scanFromSupabase(): Promise<AudioTrack[]> {
    try {
      const { supabase } = await import('../lib/supabaseClient');
      const BUCKET = 'audio-files';

      const { data, error } = await supabase
        .from('tracks')
        .select('id, title, artist, category, duration, storage_path')
        .eq('is_built_in', true)
        .order('playlist_order', { ascending: true });

      if (error) {
        console.warn('[FolderScanner] Supabase query failed, falling back to manifest:', error.message);
        return this.scanFromManifest();
      }

      return (data ?? [])
        .filter((row) => validCategories.includes(row.category as PlaylistCategory))
        .map((row) => {
          const { data: urlData } = supabase.storage
            .from(BUCKET)
            .getPublicUrl(row.storage_path as string);

          return {
            id: row.id as string,
            title: row.title as string,
            artist: (row.artist as string) ?? 'Archivo Remoto',
            category: row.category as PlaylistCategory,
            sourceType: 'local' as const,
            url: urlData.publicUrl,
            duration: (row.duration as number) ?? durationMap[row.category as PlaylistCategory] ?? 12,
            isBuiltIn: true,
          };
        });
    } catch (e) {
      console.warn('[FolderScanner] Supabase scan failed, falling back to manifest:', e);
      return this.scanFromManifest();
    }
  }

  /**
   * Legacy fallback: fetch /audio-manifest.json written by the Vite audioManifestPlugin
   * (files placed in public/audio/<category>/).
   */
  private static async scanFromManifest(): Promise<AudioTrack[]> {
    const tracks: AudioTrack[] = [];

    try {
      const response = await fetch('/audio-manifest.json');
      const manifest: AudioManifestEntry[] = await response.json();

      manifest.forEach(({ category, fileName }) => {
        const folderName = category as PlaylistCategory;
        if (!validCategories.includes(folderName)) return;

        const cleanTitle = fileName
          .replace(/\.[^/.]+$/, '')
          .replace(/[-_]/g, ' ')
          .replace(/\b\w/g, (l) => l.toUpperCase())
          .trim();

        const audioUrl = `/audio/${folderName}/${encodeURIComponent(fileName)}`;

        tracks.push({
          id: `scanned-${folderName}-${encodeURIComponent(cleanTitle.toLowerCase().replace(/\s+/g, '-'))}`,
          title: cleanTitle,
          artist: 'Archivo Local de Carpeta',
          category: folderName,
          sourceType: 'local',
          url: audioUrl,
          duration: durationMap[folderName] || 12,
          isBuiltIn: false,
        });
      });
    } catch (e) {
      console.warn('Error scanning audio folders:', e);
    }

    return tracks;
  }
}
