import type { AudioTrack, PlaylistCategory } from '../types/audio';

interface AudioManifestEntry {
  category: string;
  fileName: string;
}

/**
 * Discovers audio files placed inside public/audio/ subfolders via a JSON manifest
 * generated by the `audio-manifest` Vite plugin (see vite.config.ts). Fetching a
 * manifest + referencing plain /audio/... URLs keeps these files out of Vite/Rollup's
 * asset pipeline entirely, so the (large) mp3s are never hashed or duplicated into
 * dist/assets on every build — they're just copied once as static publicDir files.
 */
export class FolderScannerService {
  private static cachedTracksPromise: Promise<AudioTrack[]> | null = null;

  public static scanAudioFolders(): Promise<AudioTrack[]> {
    if (!this.cachedTracksPromise) {
      this.cachedTracksPromise = this.doScan();
    }
    return this.cachedTracksPromise;
  }

  private static async doScan(): Promise<AudioTrack[]> {
    const tracks: AudioTrack[] = [];

    try {
      const response = await fetch('/audio-manifest.json');
      const manifest: AudioManifestEntry[] = await response.json();

      const validCategories: PlaylistCategory[] = [
        'presentation',
        'point_intros',
        'technical_timeouts',
        'super_spike',
        'monster_block',
        'ace',
        'timeout_continuous',
        'awards',
      ];

      const durationMap: Record<PlaylistCategory, number> = {
        presentation: 180,
        point_intros: 12,
        technical_timeouts: 60,
        super_spike: 12,
        monster_block: 12,
        ace: 12,
        timeout_continuous: 180,
        awards: 180,
      };

      manifest.forEach(({ category, fileName }) => {
        const folderName = category as PlaylistCategory;
        if (!validCategories.includes(folderName)) return;

        // Format title: remove extension, replace _ and - with spaces, capitalize words
        const cleanTitle = fileName
          .replace(/\.[^/.]+$/, '')
          .replace(/[-_]/g, ' ')
          .replace(/\b\w/g, (l) => l.toUpperCase())
          .trim();

        const audioUrl = `/audio/${folderName}/${encodeURIComponent(fileName)}`;

        tracks.push({
          id: `scanned-${folderName}-${encodeURIComponent(cleanTitle.toLowerCase().replace(/\s+/g, '-'))}`,
          title: cleanTitle,
          artist: 'Archivo Local de Carpeta',
          category: folderName,
          sourceType: 'local',
          url: audioUrl,
          duration: durationMap[folderName] || 12,
          isBuiltIn: false,
        });
      });
    } catch (e) {
      console.warn('Error scanning audio folders:', e);
    }

    return tracks;
  }
}
